# Dublin Airport Activity Analysis

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [11]:
dataset = pd.read_csv('TAM07.20261011T121006.csv')

In [12]:
dataset.head()

,Statistic Label,Month,Airports in Ireland,Country,Direction,Flight Type,UNIT,VALUE
0,Passengers,2020 January,All main airports,All Countries,All directions,All flights,Thousand,2388.4
1,Passengers,2020 January,All main airports,All Countries,All directions,Scheduled,Thousand,2365.5
2,Passengers,2020 January,All main airports,All Countries,All directions,Unscheduled,Thousand,22.8
3,Passengers,2020 January,All main airports,All Countries,Arrival,All flights,Thousand,1200.0
4,Passengers,2020 January,All main airports,All Countries,Arrival,Scheduled,Thousand,1187.7

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 745524 entries, 0 to 745523
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Statistic Label      745524 non-null  object
 1   Month                745524 non-null  object
 2   Airports in Ireland  745524 non-null  object
 3   Country              745524 non-null  object
 4   Direction            745524 non-null  object
 5   Flight Type          745524 non-null  object
 6   UNIT                 745524 non-null  object
 7   VALUE                745524 non-null  float64
dtypes: float64(1), object(7)
memory usage: 45.5+ MB

In [14]:
dataset.shape

(745524, 8)

In [16]:
dataset['Statistic Label'].unique()

array(['Passengers', 'Freight', 'Commercial Flights'], dtype=object)

In [17]:
dataset['Direction'].unique()

array(['All directions', 'Arrival', 'Departure'], dtype=object)

In [18]:
dataset['Flight Type'].unique()

array(['All flights', 'Scheduled', 'Unscheduled'], dtype=object)

In [19]:
dataset['Airports in Ireland'].unique()

array(['All main airports', 'Cork', 'Dublin', 'Kerry', 'Knock', 'Shannon'],
      dtype=object)

In [20]:
dataset['Country'].unique()

array(['All Countries', 'Ireland (domestic)', 'Austria', 'Belgium',
       'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia',
       'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Italy',
       'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands',
       'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain',
       'Canary Islands', 'Sweden', 'EU27 excl Ireland 2020',
       'United Kingdom (1)', 'England', 'Northern Ireland', 'Scotland',
       'Wales', 'Other UK (1)', 'Iceland', 'Norway', 'Russia', 'Serbia',
       'Switzerland', 'Turkiye', 'Other Europe (3)',
       'Europe (48 Countries)', 'America', 'Canada', 'United States',
       'Other America (5)', 'Africa (9)', 'Eygpt', 'Morocco', 'Tunisia',
       'Other Africa (6)', 'Asia (8)', 'Bahrain', 'Israel',
       'United Arab Emirates', 'Other Asian countries (4)',
       'Oceania and Polar regions (1)'], dtype=object)

In [21]:
dataset['Month'].unique()

array(['2020 January', '2020 February', '2020 March', '2020 April',
       '2020 May', '2020 June', '2020 July', '2020 August',
       '2020 September', '2020 October', '2020 November', '2020 December',
       '2021 January', '2021 February', '2021 March', '2021 April',
       '2021 May', '2021 June', '2021 July', '2021 August',
       '2021 September', '2021 October', '2021 November', '2021 December',
       '2022 January', '2022 February', '2022 March', '2022 April',
       '2022 May', '2022 June', '2022 July', '2022 August',
       '2022 September', '2022 October', '2022 November', '2022 December',
       '2023 January', '2023 February', '2023 March', '2023 April',
       '2023 May', '2023 June', '2023 July', '2023 August',
       '2023 September', '2023 October', '2023 November', '2023 December',
       '2024 January', '2024 February', '2024 March', '2024 April',
       '2024 May', '2024 June', '2024 July', '2024 August',
       '2024 September', '2024 October', '2024 November', '2024 December',
       '2025 January', '2025 February', '2025 March', '2025 April',
       '2025 May', '2025 June', '2025 July', '2025 August',
       '2025 September', '2025 October', '2025 November', '2025 December',
       '2026 January', '2026 February', '2026 March', '2026 April',
       '2026 May', '2026 June'], dtype=object)

In [22]:
dataset['UNIT'].unique()

array(['Thousand', '000 Tonnes'], dtype=object)

In [23]:
dataset.duplicated().sum()

np.int64(0)

The purpose of this inspection is to understand the structure and categories of the file before preparing the data for modelling.
The dataset contains 745,524 rows and 8 columns, covering January 2020 to June 2026.
No null values or exact duplicate rows were detected. The categories were also reviewed to distinguish individual records from aggregated totals and avoid double counting during data preparation. The original data has not been modified at this stage.

In [24]:
dublin_activity = dataset[dataset['Airports in Ireland']== 'Dublin'].copy()

In [25]:
dublin_activity.head()

,Statistic Label,Month,Airports in Ireland,Country,Direction,Flight Type,UNIT,VALUE
1062,Passengers,2020 January,Dublin,All Countries,All directions,All flights,Thousand,2082.5
1063,Passengers,2020 January,Dublin,All Countries,All directions,Scheduled,Thousand,2064.5
1064,Passengers,2020 January,Dublin,All Countries,All directions,Unscheduled,Thousand,18.0
1065,Passengers,2020 January,Dublin,All Countries,Arrival,All flights,Thousand,1051.9
1066,Passengers,2020 January,Dublin,All Countries,Arrival,Scheduled,Thousand,1042.5

In [26]:
dublin_activity.shape

(124254, 8)

In [27]:
dublin_totals = dublin_activity[dublin_activity['Country']== 'All Countries'].copy()

In [28]:
dublin_totals.shape

(2106, 8)

In [29]:
dublin_all_flights = dublin_totals[dublin_totals['Flight Type']== 'All flights'].copy()

In [30]:
dublin_all_flights.shape

(702, 8)

In [31]:
dublin_clustering = dublin_all_flights[dublin_all_flights['Direction'].isin(['Arrival','Departure'])].copy()

In [32]:
dublin_clustering.shape

(468, 8)

In [33]:
dublin_clustering.duplicated(subset=['Month','Statistic Label','Direction']).sum()

np.int64(0)

In [34]:
dublin_clustering.groupby('Month').size()

Month
2020 April       6
2020 August      6
2020 December    6
2020 February    6
2020 January     6
                ..
2026 February    6
2026 January     6
2026 June        6
2026 March       6
2026 May         6
Length: 78, dtype: int64

In [35]:
dublin_clustering.groupby('Month').size().value_counts()

6    78
Name: count, dtype: int64

In [36]:
dublin_clustering['Month'] = pd.to_datetime(dublin_clustering['Month'], format='%Y %B')

In [37]:
dublin_clustering['Month'].head()

1065   2020-01-01
1068   2020-01-01
4251   2020-02-01
4254   2020-02-01
7437   2020-03-01
Name: Month, dtype: datetime64[ns]

In [38]:
dublin_monthly = dublin_clustering.pivot(
    index='Month',
    columns=['Statistic Label','Direction'],
    values='VALUE'
)

In [39]:
dublin_monthly.head()

Statistic Label Passengers           Freight           Commercial Flights  \
Direction          Arrival Departure Arrival Departure            Arrival
Month
2020-01-01          1051.9    1030.6     6.2       5.4                8.0
2020-02-01          1020.0    1010.7     5.6       5.4                7.6
2020-03-01           523.2     502.8     5.9       5.3                6.2
2020-04-01            11.5      12.5     4.4       3.3                0.8
2020-05-01            19.0      23.7     6.1       4.0                1.0

Statistic Label
Direction       Departure
Month
2020-01-01            8.0
2020-02-01            7.6
2020-03-01            6.1
2020-04-01            0.8
2020-05-01            0.9

In [40]:
dublin_monthly.shape

(78, 6)

In [41]:
dublin_monthly.isna().sum()

Statistic Label     Direction
Passengers          Arrival      0
                    Departure    0
Freight             Arrival      0
                    Departure    0
Commercial Flights  Arrival      0
                    Departure    0
dtype: int64

In [42]:
dublin_monthly.index.is_monotonic_increasing

True

In [43]:
expected_months = pd.date_range(
    start=dublin_monthly.index.min(),
    end=dublin_monthly.index.max(),
    freq = 'MS'
)

In [44]:
expected_months.difference(dublin_monthly.index)

DatetimeIndex([], dtype='datetime64[ns]', freq='MS')

## Data preparation
Records for Dublin Airport covering all countries and all flight types were selected. To keep arrivals and departures separate. "All directions"was excluded from this working table.

The selection contained 468 rows. Checks confirmed that there were no duplicate combinations of month, measure and direction, and that each month contained 6 records: passengers,freight and commercial flights, each separated into arrivals and departures.

The month was converted to a date format,and the measures were reorganised into columns. The resulting table contains 78 months and 6 numerical measures. Checks confirmed that the dates were in chronological order, that no months were missing between January 2020 and June 2026, and that none of the 6 measures contained null values.